project_id = "edmekawuejasnnreiwkw"

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[db]
port = 54322

[db.pooler]
enabled = true
port = 54329